Billetera/Billetera.WebApi/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using Billetera.WebApi.Areas.HelpPage.ModelDescriptions;

namespace Billetera.WebApi.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

Billetera/Billetera.WebApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Billetera.WebApi.Areas.HelpPage.ModelDescriptions;
using Billetera.WebApi.Areas.HelpPage.Models;

namespace Billetera.WebApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Billetera/Billetera.WebApi/Controllers/CuentaController.cs
using Billetera.Entidades;
using Billetera.Entidades.Parametros;
using Billetera.Negocio;
using Billetera.Negocio.Impl;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;

namespace Billetera.WebApi.Controllers
{
    public class CuentaController : ApiController
    {
        private IServiceTransaccion _service;

        public CuentaController()
        {
            this._service = new ServiceTransaccion();
        }

        [HttpGet]
        public Cuenta Get(long id)
        {
            return this._service.GetCuenta(id);
        }

        [HttpPost]
        public Cuenta RegistrarTransaccion([FromBody]NuevaTransaccionParametros param)
        {
            return this._service.RegistroNuevaTransaccion(param);
        }
    }
}

Billetera/Billetera.WebApi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Billetera.WebApi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

Billetera/Billetera.WebApi/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Billetera.WebApi.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

Billetera/Billetera.WebApi/Views/Home/Index.cshtml
@using Billetera.Entidades.Parametros;
@using Billetera.Entidades.Numeracion;
@model NuevaTransaccionParametros
@{
    List<SelectListItem> tipos = new List<SelectListItem>
{
new SelectListItem()
{
Value = ((short)TipoTransaccion.Incremento).ToString(),
Text = "Incremento",
Selected = true
},
new SelectListItem()
{
Value = ((short)TipoTransaccion.Decremento).ToString(),
Text = "Decremento",
Selected = false
}
};
}
<div class="jumbotron">
    <h1>Billetera</h1>
</div>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Cuenta", "api", FormMethod.Post, new { @id = "formPost", style = "width:100%;" }))
        {
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CuentaId)
                            @Html.TextBoxFor(model => model.CuentaId, new { @class = "form-control", @type = "number", @required = "" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Tipo)
                            @Html.DropDownListFor(model => model.Tipo, tipos, new { @class = "form-control", @required = "" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Cantidad)
                            @Html.TextBoxFor(model => model.Cantidad, new { @class = "form-control", @type = "number", @required = "" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Concepto)
                            @Html.TextBoxFor(model => model.Concepto, new { @class = "form-control", @type = "text" })
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <br>
                        <button id="btnRegister" name="btnRegister" type="submit" class="btn btn-primary">
                            Guardar
                        </button>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-12">
        <h3><strong>Saldo:</strong></h3>
        <span id="Saldo" name="Saldo"></span>
        <h3><strong>Detalle</strong></h3>
        <div class="table-responsive">
            <table class="table table-small-font table-bordered" cellspacing="0">
                <thead>
                    <tr>
                        <th>Tipo</th>
                        <th>Monto</th>
                        <th>Concepto</th>
                    </tr>
                </thead>
                <tbody id="body_table"></tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript" src="~/Scripts/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="~/Scripts/jquery.form.js"></script>

<script>
    $(document).ready(function () {
        $('#formPost').submit(function (e) {
            e.preventDefault();
            $('#formPost').ajaxSubmit({
                type: "POST",
                dataType: "json",
                success: function (response) {
                    $('#Saldo').html(response.Saldo);
                    var renderBody = '';
                    for (var i = 0; i < response.Detalle.length; i++) {
                        var item = response.Detalle[i];
                        var tmprow = $('#tmpl_row').text();
                        tmprow = tmprow.replace('{{Type}}', item.Tipo == 1 ? 'Incremento' : 'Decremento');
                        tmprow = tmprow.replace('{{Amount}}', item.Cantidad);
                        tmprow = tmprow.replace('{{Concept}}', item.Concepto);
                        renderBody = renderBody + tmprow;
                    }
                    $('#body_table').html(renderBody);
                },
                error: function (response) {
                    alert(response.responseJSON.ExceptionMessage);
                }
            });
            return false;
        });
    });
</script>


<script id="tmpl_row" type="text/html">
    <tr>
        <td>{{Type}}</td>
        <td>{{Amount}}</td>
        <td>{{Concept}}</td>
    </tr>
</script>

Billetera/Billetera.WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.form.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>